### ISSUE TITLE
Will you be showing the different ways of Interacting with GitHub? 

### ISSUE THREAD

**Issue by aaronkellyuk** [finneyj/SaadBall#6]
Just a thought that there are multiple ways to interact with platforms like GitHub. There is the "git" command that you have used so far, but then there is also the dedicated GitHub CLI that can be used, or other OS applications like LazyGit or GitUI.

**Comment by aaronkellyuk** [comment]
There is also the GitHub desktop client.

**Comment by ezzini** [comment]
Thanks for mentioning that. GitHub CLI (gh) comes with powerful features indeed. I think that GitHub Desktop was mentioned by Joe on Friday.  
We focused on 'git' as it is universal and can be used with different version control systems e.g., GitLab.
